extern const GeoLayout slime_princess_Anim_State_Switch_opt1[];
extern const GeoLayout slime_princess_geo[];
extern Lights1 slime_princess_Slime_Princess_Body_lights;
extern Lights1 slime_princess_Slime_Princess_Face_lights;
extern Lights1 slime_princess_Slime_Princess_Crown_Jewel_lights;
extern Lights1 slime_princess_Dirtiest_lights;
extern u8 slime_princess_Slime_Princess_Face_rgba16[];
extern u8 slime_princess_Slime_Princess_Crown_Jewel_ci8[];
extern u8 slime_princess_Slime_Princess_Crown_Jewel_pal_rgba16[];
extern u8 slime_princess_Dirtiest_ci4[];
extern u8 slime_princess_Dirtiest_pal_rgba16[];
extern Vtx slime_princess_Body_mesh_layer_1_vtx_0[59];
extern Gfx slime_princess_Body_mesh_layer_1_tri_0[];
extern Vtx slime_princess_Body_mesh_layer_1_vtx_1[9];
extern Gfx slime_princess_Body_mesh_layer_1_tri_1[];
extern Vtx slime_princess_Body_mesh_layer_1_vtx_2[86];
extern Gfx slime_princess_Body_mesh_layer_1_tri_2[];
extern Gfx mat_slime_princess_Slime_Princess_Body[];
extern Gfx mat_slime_princess_Slime_Princess_Face[];
extern Gfx mat_slime_princess_Slime_Princess_Crown_Jewel[];
extern Gfx mat_revert_slime_princess_Slime_Princess_Crown_Jewel[];
extern Gfx mat_slime_princess_Dirtiest[];
extern Gfx mat_revert_slime_princess_Dirtiest[];
extern Gfx slime_princess_Body_mesh_layer_1[];
extern Gfx slime_princess_Body_mesh_layer_1_mat_override_Dirtiest_0[];
