extern const GeoLayout treadmill_Anim_opt1[];
extern const GeoLayout treadmill_Anim_opt2[];
extern const GeoLayout treadmill_Anim_opt3[];
extern const GeoLayout treadmill_geo[];
extern Lights1 treadmill_f3dlite_material_003_lights;
extern Lights1 treadmill_f3dlite_material_002_lights;
extern Lights1 treadmill_f3dlite_material_001_lights;
extern Lights1 treadmill_f3dlite_material_lights;
extern Lights1 treadmill_f3dlite_material_004_lights;
extern Lights1 treadmill_f3dlite_material_005_lights;
extern u8 treadmill_ttc_textures_06000_rgba16_i8[];
extern u8 treadmill_ttc_textures_05800_rgba16_i8[];
extern u8 treadmill__2_rgba16_i8[];
extern u8 treadmill__1_rgba16_i8[];
extern u8 treadmill__0_rgba16_i8[];
extern u8 treadmill___rgba16_i8[];
extern Vtx treadmill_tread_mesh_layer_1_vtx_0[24];
extern Gfx treadmill_tread_mesh_layer_1_tri_0[];
extern Vtx treadmill_tread_mesh_layer_1_vtx_1[8];
extern Gfx treadmill_tread_mesh_layer_1_tri_1[];
extern Vtx treadmill_tread_mesh_layer_1_vtx_2[19];
extern Gfx treadmill_tread_mesh_layer_1_tri_2[];
extern Gfx mat_treadmill_f3dlite_material_003[];
extern Gfx mat_treadmill_f3dlite_material_002[];
extern Gfx mat_treadmill_f3dlite_material_001[];
extern Gfx mat_treadmill_f3dlite_material[];
extern Gfx mat_treadmill_f3dlite_material_004[];
extern Gfx mat_treadmill_f3dlite_material_005[];
extern Gfx treadmill_tread_mesh_layer_1[];
extern Gfx treadmill_tread_mesh_layer_1_mat_override_f3dlite_material_0[];
extern Gfx treadmill_tread_mesh_layer_1_mat_override_f3dlite_material_004_1[];
extern Gfx treadmill_tread_mesh_layer_1_mat_override_f3dlite_material_005_2[];
extern Gfx treadmill_material_revert_render_settings[];
