extern const GeoLayout slime_prince_Anim_State_Switch_opt1[];
extern const GeoLayout slime_prince_geo[];
extern Lights1 slime_prince_Slime_Prince_Body_lights;
extern Lights1 slime_prince_Slime_Prince_Face_lights;
extern Lights1 slime_prince_Slime_Prince_Crown_Jewel_lights;
extern Lights1 slime_prince_Dirtiest_lights;
extern u8 slime_prince_Slime_Prince_Face_rgba16[];
extern u8 slime_prince_Slime_Prince_Crown_Jewel_rgba16[];
extern u8 slime_prince_Dirtiest_ci4[];
extern u8 slime_prince_Dirtiest_pal_rgba16[];
extern Vtx slime_prince_Body_mesh_layer_1_vtx_0[59];
extern Gfx slime_prince_Body_mesh_layer_1_tri_0[];
extern Vtx slime_prince_Body_mesh_layer_2_vtx_0[9];
extern Gfx slime_prince_Body_mesh_layer_2_tri_0[];
extern Vtx slime_prince_Body_mesh_layer_2_vtx_1[44];
extern Gfx slime_prince_Body_mesh_layer_2_tri_1[];
extern Gfx mat_slime_prince_Slime_Prince_Body[];
extern Gfx mat_slime_prince_Slime_Prince_Face[];
extern Gfx mat_slime_prince_Slime_Prince_Crown_Jewel[];
extern Gfx mat_revert_slime_prince_Slime_Prince_Crown_Jewel[];
extern Gfx mat_slime_prince_Dirtiest[];
extern Gfx mat_revert_slime_prince_Dirtiest[];
extern Gfx slime_prince_Body_mesh_layer_1[];
extern Gfx slime_prince_Body_mesh_layer_1_mat_override_Dirtiest_0[];
extern Gfx slime_prince_Body_mesh_layer_2[];
extern Gfx slime_prince_Body_mesh_layer_2_mat_override_Dirtiest_0[];
