extern const GeoLayout fairy_Anim_State_Switch_opt1[];
extern const GeoLayout fairy_Anim_State_Switch_opt2[];
extern const GeoLayout fairy_geo[];
extern Lights1 fairy_Fairy_Body_0_lights;
extern Lights1 fairy_Fairy_Body_1_lights;
extern Lights1 fairy_Fairy_Body_2_lights;
extern Lights1 fairy_Fairy_Wings_lights;
extern u8 fairy_fairy0_ia8[];
extern u8 fairy_fairy1_ia8[];
extern u8 fairy_fairy2_ia8[];
extern u8 fairy_Fairy_Wing_ia8[];
extern Vtx fairy_Head_mesh_layer_4_vtx_0[9];
extern Gfx fairy_Head_mesh_layer_4_tri_0[];
extern Vtx fairy_LeftWing_mesh_layer_4_vtx_0[4];
extern Gfx fairy_LeftWing_mesh_layer_4_tri_0[];
extern Vtx fairy_RightWing_mesh_layer_4_vtx_0[4];
extern Gfx fairy_RightWing_mesh_layer_4_tri_0[];
extern Gfx mat_fairy_Fairy_Body_0[];
extern Gfx mat_fairy_Fairy_Body_1[];
extern Gfx mat_fairy_Fairy_Body_2[];
extern Gfx mat_fairy_Fairy_Wings[];
extern Gfx mat_revert_fairy_Fairy_Wings[];
extern Gfx fairy_Head_mesh_layer_4[];
extern Gfx fairy_Head_mesh_layer_4_mat_override_Fairy_Body_1_0[];
extern Gfx fairy_Head_mesh_layer_4_mat_override_Fairy_Body_2_1[];
extern Gfx fairy_LeftWing_mesh_layer_4[];
extern Gfx fairy_LeftWing_mesh_layer_4_mat_override_Fairy_Body_1_0[];
extern Gfx fairy_LeftWing_mesh_layer_4_mat_override_Fairy_Body_2_1[];
extern Gfx fairy_RightWing_mesh_layer_4[];
extern Gfx fairy_RightWing_mesh_layer_4_mat_override_Fairy_Body_1_0[];
extern Gfx fairy_RightWing_mesh_layer_4_mat_override_Fairy_Body_2_1[];
