extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_f3dlite_material_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_001_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_004_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_002_lights;
extern u8 castle_grounds_dl_studtop_ci8[];
extern u8 castle_grounds_dl_studtop_ci8_pal_rgba16[];
extern u8 castle_grounds_dl_studbottom_ci8[];
extern u8 castle_grounds_dl_studbottom_ci8_pal_rgba16[];
extern u8 castle_grounds_dl_spawn_i8[];
extern Vtx castle_grounds_dl_Baseplate_mesh_layer_1_vtx_0[20];
extern Gfx castle_grounds_dl_Baseplate_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Baseplate_mesh_layer_1_vtx_1[4];
extern Gfx castle_grounds_dl_Baseplate_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Death_Plane_mesh_layer_5_vtx_0[4];
extern Gfx castle_grounds_dl_Death_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_004[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx castle_grounds_dl_Baseplate_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_Death_Plane_mesh_layer_5[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
