smlua_text_utils_course_acts_replace(COURSE_BOB, (" 1 INERTIA FACTORY"),	("THANKS FOR PLAYING"),	("FOOTRACE WITH KOOPA THE QUICK"),	("SHOOT TO THE ISLAND IN THE SKY"),	("FIND THE 8 RED COINS"),	("MARIO WINGS TO THE SKY"),	("BEHIND CHAIN CHOMP'S GATE"))

